### PR TITLE
Refactor JSON in JUnit tests

### PR DESCRIPTION
**Pull request by helloworld12321**
Okay, this is a *very* minor issue, but the formatting of the JUnit tests used to be kind of intimidating. (There are still a lot of escaped characters, but hopefully it should be a bit easier to read now! ☺️)

### CODE REVIEW

**Comment by floogulinc** [comment]
I noticed some of these don't have the keys in quotes so they aren't actually valid JSON. I guess the parser doesn't mind but maybe we should either make them valid JSON or switch to building the documents using `.append()` chains.

**Comment by helloworld12321** [comment]
Oh my gosh, I didn't even notice! Let me go fix that.

**Review by floogulinc — APPROVED** [review]
Thanks

**Review by floogulinc — APPROVED** [review]

**Review by NicMcPhee — APPROVED** [review]
SOOOO much better! 😀

Anyone got any ideas on how to make the various `newTestUser`s at the end less intimidating?

**Comment by floogulinc** [comment]
> SOOOO much better! 😀
> 
> Anyone got any ideas on how to make the various `newTestUser`s at the end less intimidating?

Since those tests are testing the creation of users I think we want to just have the JSON the "client" is sending like that.

**Comment by helloworld12321** [comment]
> > SOOOO much better! 😀
> > Anyone got any ideas on how to make the various `newTestUser`s at the end less intimidating?
> 
> Since those tests are testing the creation of users I think we want to just have the JSON the "client" is sending like that.

Yeah, I considered making those `Document`s too, but it seemed like kind of a waste if we were just going to convert them back into strings ¯\\\_(ツ)\_/¯

**Comment by helloworld12321** [comment]
Since this has two approvals, I think I'm going to go ahead and merge it. Thanks, everyone!

**Comment by helloworld12321** [comment]
> > > SOOOO much better! 😀
> > > Anyone got any ideas on how to make the various `newTestUser`s at the end less intimidating?
> > 
> > 
> > Since those tests are testing the creation of users I think we want to just have the JSON the "client" is sending like that.
> 
> Yeah, I considered making those `Document`s too, but it seemed like kind of a waste if we were just going to convert them back into strings ¯\_(ツ)_/¯

It's a bit of a pity that multiline strings are only available starting in [Java 13](https://openjdk.java.net/jeps/355)! 🙂

**Pull request merged**
