### PR TITLE
Clean up mongoseed.sh

### PR DESCRIPTION
**Pull request by helloworld12321**
`mongoseed.sh` errors out in a couple of scenarios.

- It doesn't like it if there are no json files; in that case, it tries to literally import a file named `*.json` (which of course doesn't exist).
- It doesn't like it if any of your json files have spaces in their name, because `$file` isn't quoted.
- It doesn't like it if the path to mongoseed.sh has spaces, because `$BASH_SOURCE` isn't quoted. (But usually, this isn't an issue since in most invocations the path is just `.`)
- It has strange behavior if the $MONGO_DB environment variable contains spaces, because neither $MONGO_DB nor $SEED_DB are quoted (For example, if you do export MONGO_DB='dev --help' and then run mongoseed.sh, instead of seeding the database, it will give you the help pages for mongo and mongoimport.)

This commit fixes the first issue by checking to make sure that the file exists before importing it; this catches the case where `mongoseed.sh` tries to import a file named `*.json`. This commit fixes the three other issues by quoting variables in the appropriate places.

Also, this commit renames `$SEED_DB` to `$seed_db`. Since this is a local variable, not an environment variable, it gets a lower case name.

### CODE REVIEW

**Comment by floogulinc** [comment]
Do you know of databases or collections with spaces are legal in mongo?

**Comment by floogulinc** [comment]
These changes need to be tested in the Docker deployment before accepting.

**Comment by helloworld12321** [comment]
⬆️ Roger that! ☺️

⬆️⬆️ Databases with spaces are forbidden, but it looks like collections with spaces are allowed:

Screen Shot 2020-03-04 at 9 14 15 AM

Screen Shot 2020-03-04 at 9 17 17 AM

I've put quotes around `$MONGO_DB` mainly for consistency, and because it gives better error reporting that way—without the quotes, it gives a cryptic `only one positional argument allowed` message:

Screen Shot 2020-03-04 at 9 19 21 AM

(And then there are shenanigans like `export MONGO_DB='dev --eval "arbitrary code"'` 😛)

**Comment by helloworld12321** [comment]
A (possibly more idiomatic) alternative to using `[[ -f "$file" ]]` would be to set `shopt -s nullglob` at the beginning of the script—see https://unix.stackexchange.com/a/293650

If you want me to use that instead, I'd be happy to change it 😊

**Comment by floogulinc** [comment]
I just tested this with Docker and it worked. I didn't do any tests with no seed files though.

```
Attaching to 3601-iteration-template_mongo_1
[36mmongo_1][0m about to fork child process, waiting until server is ready for connections.
[36mmongo_1][0m forked process: 27
[36mmongo_1][0m 2020-04-16T15:55:25.346+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] MongoDB starting : pid=27 port=27017 dbpath=/data/db 64-bit host=dfc5fcce8172
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] db version v3.4.23
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] git version: 324017ede1dbb1c9554dd2dceb15f8da3c59d0e8
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] modules: none
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] build environment:
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten]     distarch: x86_64
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[36mmongo_1][0m 2020-04-16T15:55:25.349+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27017, ssl: { mode: "disabled" } }, processManagement: { fork: true, pidFilePath: "/tmp/docker-entrypoint-temp-mongod.pid" }, systemLog: { destination: "file", logAppend: true, path: "/proc/1/fd/1" } }
[36mmongo_1][0m 2020-04-16T15:55:25.350+0000 I STORAGE  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:25.350+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[36mmongo_1][0m 2020-04-16T15:55:25.350+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[36mmongo_1][0m 2020-04-16T15:55:25.351+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1457M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
[36mmongo_1][0m 2020-04-16T15:55:25.415+0000 I CONTROL  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:25.415+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[36mmongo_1][0m 2020-04-16T15:55:25.415+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[36mmongo_1][0m 2020-04-16T15:55:25.416+0000 I CONTROL  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:25.441+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[36mmongo_1][0m 2020-04-16T15:55:25.477+0000 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
[36mmongo_1][0m 2020-04-16T15:55:25.477+0000 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
[36mmongo_1][0m 2020-04-16T15:55:25.478+0000 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
[36mmongo_1][0m 2020-04-16T15:55:25.478+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
[36mmongo_1][0m 2020-04-16T15:55:25.479+0000 I NETWORK  [thread1] waiting for connections on port 27017
[36mmongo_1][0m child process started successfully, parent exiting
[36mmongo_1][0m 2020-04-16T15:55:25.516+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:33532 #1 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:25.516+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:33532 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.23" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
[36mmongo_1][0m 
[36mmongo_1][0m 2020-04-16T15:55:25.520+0000 I -        [conn1] end connection 127.0.0.1:33532 (1 connection now open)
[36mmongo_1][0m /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mongoseed.sh
[36mmongo_1][0m Dropping DB prod
[36mmongo_1][0m MongoDB shell version v3.4.23
[36mmongo_1][0m connecting to: mongodb://127.0.0.1:27017/prod
[36mmongo_1][0m 2020-04-16T15:55:25.561+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:33534 #2 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:25.563+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:33534 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.23" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
[36mmongo_1][0m MongoDB server version: 3.4.23
[36mmongo_1][0m { "ok" : 1 }
[36mmongo_1][0m 2020-04-16T15:55:25.568+0000 I -        [conn2] end connection 127.0.0.1:33534 (1 connection now open)
[36mmongo_1][0m Seeding users from /docker-entrypoint-initdb.d/seed/users.json in DB prod
[36mmongo_1][0m 2020-04-16T15:55:25.583+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:33536 #3 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:25.586+0000	connected to: localhost
[36mmongo_1][0m 2020-04-16T15:55:25.606+0000	imported 10 documents
[36mmongo_1][0m 2020-04-16T15:55:25.606+0000 I -        [conn3] end connection 127.0.0.1:33536 (1 connection now open)
[36mmongo_1][0m 
[36mmongo_1][0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/seed
[36mmongo_1][0m 
[36mmongo_1][0m 2020-04-16T15:55:25.613+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
[36mmongo_1][0m killing process with pid: 27
[36mmongo_1][0m 2020-04-16T15:55:25.615+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I NETWORK  [signalProcessingThread] closing listening socket: 8
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I NETWORK  [signalProcessingThread] closing listening socket: 9
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I NETWORK  [signalProcessingThread] shutdown: going to flush diaglog...
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
[36mmongo_1][0m 2020-04-16T15:55:25.616+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
[36mmongo_1][0m 2020-04-16T15:55:25.747+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
[36mmongo_1][0m 2020-04-16T15:55:25.747+0000 I CONTROL  [signalProcessingThread] now exiting
[36mmongo_1][0m 2020-04-16T15:55:25.747+0000 I CONTROL  [initandlisten] shutting down with code:0
[36mmongo_1][0m 
[36mmongo_1][0m MongoDB init process complete; ready for start up.
[36mmongo_1][0m 
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=dfc5fcce8172
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] db version v3.4.23
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] git version: 324017ede1dbb1c9554dd2dceb15f8da3c59d0e8
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] modules: none
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] build environment:
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten]     distarch: x86_64
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[36mmongo_1][0m 2020-04-16T15:55:26.633+0000 I CONTROL  [initandlisten] options: {}
[36mmongo_1][0m 2020-04-16T15:55:26.635+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[36mmongo_1][0m 2020-04-16T15:55:26.635+0000 I STORAGE  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:26.635+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[36mmongo_1][0m 2020-04-16T15:55:26.635+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[36mmongo_1][0m 2020-04-16T15:55:26.635+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1457M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
[36mmongo_1][0m 2020-04-16T15:55:26.745+0000 I STORAGE  [initandlisten] WiredTiger message [1587052526:745428][1:0x7f4f5f382d40], txn-recover: Main recovery loop: starting at 1/21376
[36mmongo_1][0m 2020-04-16T15:55:26.813+0000 I STORAGE  [initandlisten] WiredTiger message [1587052526:813710][1:0x7f4f5f382d40], txn-recover: Recovering log 1 through 2
[36mmongo_1][0m 2020-04-16T15:55:26.866+0000 I STORAGE  [initandlisten] WiredTiger message [1587052526:866649][1:0x7f4f5f382d40], txn-recover: Recovering log 2 through 2
[36mmongo_1][0m 2020-04-16T15:55:26.930+0000 I CONTROL  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:26.930+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[36mmongo_1][0m 2020-04-16T15:55:26.930+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[36mmongo_1][0m 2020-04-16T15:55:26.930+0000 I CONTROL  [initandlisten] 
[36mmongo_1][0m 2020-04-16T15:55:26.932+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[36mmongo_1][0m 2020-04-16T15:55:26.933+0000 I NETWORK  [thread1] waiting for connections on port 27017
[36mmongo_1][0m 2020-04-16T15:55:27.695+0000 I NETWORK  [thread1] connection accepted from 172.20.0.3:34620 #1 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:27.695+0000 I -        [conn1] end connection 172.20.0.3:34620 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:27.959+0000 I NETWORK  [thread1] connection accepted from 172.20.0.3:34622 #2 (1 connection now open)
[36mmongo_1][0m 2020-04-16T15:55:27.969+0000 I NETWORK  [conn2] received client metadata from 172.20.0.3:34622 conn2: { driver: { name: "mongo-java-driver|sync", version: "3.12.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.19.76-linuxkit" }, platform: "Java/IcedTea/1.8.0_212-b04" }

```

**Pull request merged**
