### PR TITLE
Increase coverage of `User.java`

### PR DESCRIPTION
**Pull request by kklamberty**
I'm not sure this is really great testing, but it does increase the coverage.

### CODE REVIEW

**Review by jpwalbran — APPROVED** [review]
Looks good.

**Review by NicMcPhee — CHANGES_REQUESTED** [review]
So this does improve the coverage, but I think it does it in the wrong place. What you're trying to do here is test the the `equals()` and `hashCode()` methods in `User`. That really should be in a new `UserSpec.java`, not being done indirectly here in the controller tests.

**Comment by kklamberty** [comment]
Oh, that totally makes sense. What I really wanted to do was use the equals method, but it was just not happening. You're right. What I actually ended up doing was something that was not a test of the controller, but rather a test of the User class. Thanks!

**Comment by NicMcPhee** [comment]
That's why we have code reviews! 😜

**Comment by kklamberty** [comment]
> I'm not sure this is really great testing, but it does increase the coverage.

I have more confidence in the tests that are included in this PR now than I did before. I think it's worth adding these tests to the repository.

**Review by NicMcPhee — APPROVED** [review]
This looks great. We probably want to also test the `hashCode()` function, but that could be in a different issue.

**Pull request merged**
