### PR TITLE
Update jasmine-core from 3.x to 4.x

### LINKED ISSUE #612: Update to Jasmine 4
To update Jasmine, we may need to update some karma-related dependencies. See: https://github.com/UMM-CSci-3601/3601-iteration-template/pull/610#issuecomment-1013784234

### PR DESCRIPTION
**Pull request by helloworld12321**
In doing so, we also need to update zone.js to the latest
point-release, because of [this bug][1].

Closes #612.

[1]: https://github.com/angular/angular/pull/45025

### CODE REVIEW

**Comment by NicMcPhee** [comment]
Do you want to include the `zone.js` library as part of this PR?

Also, BetterCodeHub seems to be hanging at the moment, which is annoying since it blocks pretty much all merges.

**Review by NicMcPhee — COMMENTED** [review]
Do we want to include the `zone.js` upgrade here as well? Or do we want to wait until I merge in the next round of Angular updates (it's been one a week for the last month) and see if that updates it for us?

Also, BetterCodeHub is hanging at the moment which is blocking all merging - sigh.

**Comment by helloworld12321** [comment]
@NicMcPhee Darn, I thought I had committed the zone update. Sorry, my mistake—let me fix that real quick.

**Comment by helloworld12321** [comment]
@NicMcPhee Fixed now!

**Comment by NicMcPhee** [comment]
I think this has been accidentally superseded (sorry!) by some of my other "Let's upgrade all the out-of-date packages" PRs. We're up to v0.11.7 of `zone.js` and v4.2.0 of `jasmine-core`. @helloworld12321 – Would you be OK if we just close this?

**Comment by helloworld12321** [comment]
@NicMcPhee Absolutely, sounds good! 🙂

**Pull request closed without merging**
